language: node_js
dist: trusty
node_js: 8.9
cache:
  directories:
  - node_modules
before_script:
- npm link
notifications:
  slack:
    secure: GC2AqNBwIByljO56UWGzp20Ko3l/y+Kp98yySetwyF1Q0WviXb9kCc9FGXXBg1V4PHTzKZ12ubldeF1IycpkXydt5jRnFQkxgtM0RrkHH2wMZDUFey1YdgmNYDBBonRBQXXFQsQEWJQbowmIC2HUDKB7YqSQB412FXHB87VXQvl3OQXWEySuiTA9++PlCEsrroLaKgisdu+KnKkY/TvqLGSH0rkgEzBzlvDinXKa5zaLaWz07Vq7UgWDloVry7LxXg/TS1AF1u53x2raAI0tut9eX+6tGhZxteJsev2e+QOxGUG/Ptl+7xX7X//9vs4njdvBcphirKYXoXoaHfAS1YQh99cKDS/Q1+jN/2kTtHvIJmZgbkLS0gj2sYuCFAhdZed3s0aqad1o+Es6+sUxC+1cAyAOyGg4chy7qzY9hZ3MNdkVh1IAki8Gnw9qzHyuaAOg1lXSbEVCgWm9yGYwHdpVOifWGbpXIo2RwTypsHxbohjO3YGx6XUe53GaMpdHFMu6y2Q0VcRoRGhU4SQsaY+Q7kFddk2SaCvISCP4X9ldF0oZZWtKKtXHTTIIoEekPO2uwiWT5E9b1BltdLtdcIi5/k7vQfP9Tp578k63J/Rm459HwUWIhbNzYRkmRjuY/Tjsm/jbGEqcF37svi2Z1S0ZBt9fSMWFiFZvUMJ5N4g=
